# Generated by Django 2.0.1 on 2018-04-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField()),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('album', models.TextField()),
                ('writer', models.TextField()),
            ],
            options={
                'ordering': ('release_date',),
            },
        ),
    ]
