# Generated by Django 2.0.12 on 2019-09-08 23:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_disasterneighborhoodgrid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AebmResults',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tract', models.BigIntegerField(blank=True, null=True)),
                ('occupancy', models.CharField(blank=True, max_length=255, null=True)),
                ('eqbldgtype', models.CharField(blank=True, max_length=255, null=True)),
                ('designleve', models.CharField(blank=True, max_length=255, null=True)),
                ('bldgvalue', models.IntegerField(blank=True, null=True)),
                ('lossstruct', models.FloatField(blank=True, null=True)),
                ('lossnonstr', models.FloatField(blank=True, null=True)),
                ('lossnons_1', models.FloatField(blank=True, null=True)),
                ('lossconten', models.FloatField(blank=True, null=True)),
                ('contentval', models.FloatField(blank=True, null=True)),
                ('casdaylvl1', models.FloatField(blank=True, null=True)),
                ('casdaylvl2', models.FloatField(blank=True, null=True)),
                ('casdaylvl3', models.FloatField(blank=True, null=True)),
                ('casdaylvl4', models.FloatField(blank=True, null=True)),
                ('casnight_1', models.FloatField(blank=True, null=True)),
                ('casnight_2', models.FloatField(blank=True, null=True)),
                ('casnight_3', models.FloatField(blank=True, null=True)),
                ('casnightlv', models.FloatField(blank=True, null=True)),
                ('loss_ratio', models.FloatField(blank=True, null=True)),
                ('designle_1', models.CharField(blank=True, max_length=255, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'aebm_results',
                'managed': False,
            },
        ),
    ]
